[tool.poetry]
name = "discussions"
version = "0.1.0"
description = ""
authors = ["Alexandru Cojocaru <hi@xojoc.pw>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = {version = "4.0a1", allow-prereleases = true}
django-ninja = "^0.16"
django-redis = "^4.12"
django-debug-toolbar = "^3.2"
whitenoise = "^5.3.0"
psycopg2-binary = "^2.8"
daphne = "^3.0.2"
celery = "^5"
setuptools = "59.0.6"
flower = "^1.0"
django-celery-beat = "^2"
django-celerybeat-status = "^0.0.10"
gevent = "^21.1"
urllib3 = "^1"
requests = "^2"
CacheControl = "^0.12"
sentry-sdk = "^1.0"
praw = "^7.2"
Markdown = "^3.3"
zstandard = "*"
python-dateutil = "^2.8.2"
importlib-metadata="*"
tweepy = "^4"
bs4 = "^0.0.1"
lxml = "^4.6.3"
archiveis = "^0.0.9"
nltk = "^3.6.5"
cleanurl = "*"
django-allauth = "^0.48.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9"
autopep8 = "*"
mypy = "^0.931"
django-stubs = "^1.9.0"
celery-stubs = "^0.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
split_before_logical_operator = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "discussions.settings"