[tool.poetry]
name = "discussions"
version = "0.1.0"
description = ""
authors = ["Alexandru Cojocaru <hi@xojoc.pw>"]

[tool.poetry.dependencies]
archiveis = "^0"
bs4 = "^0"
CacheControl = "^0"
celery = "^5"
cleanurl = "*"
crispy-bootstrap5 = "^0"
daphne = "^3"
Django = "^4"
django-allauth = "^0.51"
django-celery-beat = "^2"
#django-celery-beat = { git = "https://github.com/celery/django-celery-beat.git", branch = "master" }
django-celerybeat-status = "^0"
django-crispy-forms = "^1"
django-debug-toolbar = "^3"
django-ninja = "^0"
django-redis = "^5"
django-sass = "^1"
flower = "^1"
gevent = "^21.1"
importlib-metadata="*"
lxml = "^4.6"
Markdown = "^3.3"
minify-html = "^0"
nltk = "^3.6"
praw = "^7.2"
psycopg2-binary = "^2.8"
python = "^3.9"
python-dateutil = "^2.8"
# pytz = "2023.4"
requests = "^2"
sentry-sdk = "^1"
setuptools = "59.0.6"
stripe = "^4.1.0"
tweepy = "^4"
# tzdata = "^2022.1"
urllib3 = "^1"
whitenoise = "^6"
zstandard = "*"
django-extensions = "^3.2.1"
Jinja2 = "^3.1.2"
feedparser = "^6.0.10"

[tool.poetry.dev-dependencies]
flake8 = "^5"
autopep8 = "*"
mypy = "^0"
django-stubs = "^1"
celery-stubs = "^0"
black = "^22"
ipython = "^8.5.0"
bpython = "^0.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
split_before_logical_operator = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "discussions.settings"