[tool.poetry]
name = "discussions"
version = "0.1.0"
description = ""
authors = ["Alexandru Cojocaru <hi@xojoc.pw>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = {version = "4.0a1", allow-prereleases = true}
celery = "^5.0"
psycopg2-binary = "^2.8"
urllib3 = "^1.26"
django-redis = "^4.12"
requests = "^2.25"
CacheControl = "^0.12"
django-celerybeat-status = "^0.0.10"
sentry-sdk = "^1.0"
gevent = "^21.1"
django-celery-beat = "^2"
praw = "^7.2"
zstandard = "*"
whitenoise = "^5.3.0"
daphne = "^3.0.2"
flower = "^1.0.0"
django-debug-toolbar = "^3.2.2"
python-dateutil = "^2.8.2"
djangorestframework = "*"
Markdown = "^3.3.4"
tweepy = "^4.1.0"
bs4 = "^0.0.1"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
split_before_logical_operator = true
