# Generated by Django 3.2.6 on 2021-08-29 19:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210829_1924'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='gin_discussion_title', opclasses=['gin_trgm_ops']),
        ),
    ]
