# Generated by Django 3.2.6 on 2021-08-30 19:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_discussion_gin_discussion_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("statistics", models.JSONField(decoder=django.core.serializers.json.Deserializer, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
