# Generated by Django 3.2.6 on 2021-08-30 20:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="statistics",
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
