# Generated by Django 4.0a1 on 2021-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_statistics_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tweet_id", models.IntegerField()),
                ("bot_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discussions", models.ManyToManyField(to="web.Discussion")),
            ],
        ),
    ]
