# Generated by Django 4.0a1 on 2021-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_discussion_web_discuss_created_9d621d_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="id",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="tweet_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
