# Generated by Django 4.0a1 on 2021-12-13 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_discussion_platform_id_alter_discussion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
