# Generated by Django 4.0a1 on 2021-12-16 14:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_discussion_normalized_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_title'], name='gin_discussion_norm_title', opclasses=['gin_trgm_ops']),
        ),
    ]
