# Generated by Django 4.0a1 on 2021-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_resource_resource_index_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="status_code",
            field=models.IntegerField(null=True),
        ),
    ]
