# Generated by Django 4.0a1 on 2021-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_alter_resource_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="last_processed",
            field=models.DateTimeField(null=True),
        ),
    ]
