# Generated by Django 4.0a1 on 2021-12-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_resource_last_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='bot_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
