# Generated by Django 4.0a1 on 2022-01-10 13:36

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_mastodonpost"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="discussion",
            name="index_schemeless_story_url",
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper("schemeless_story_url"), name="varchar_pattern_ops"), name="index_schemeless_story_url"),
        ),
    ]
