# Generated by Django 4.0a1 on 2022-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_apiclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="email",
            field=models.TextField(null=True),
        ),
    ]
