# Generated by Django 4.0a1 on 2022-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_alter_apiclient_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
