# Generated by Django 4.0a1 on 2022-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0039_apiclient_url_alter_apiclient_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="anchor_rel",
            field=models.TextField(null=True),
        ),
    ]
