# Generated by Django 4.0a1 on 2022-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_alter_subscriber_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
