# Generated by Django 4.0a1 on 2022-06-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0047_alter_subscriber_topic"),
    ]

    operations = [
        # migrations.CreateModel(
        #             "id",
        #             models.BigAutoField(
        #             ),
        #         ),
        #             "password",
        #         ),
        #             "last_login",
        #             models.DateTimeField(
        #             ),
        #         ),
        #             "is_superuser",
        #             models.BooleanField(
        #             ),
        #         ),
        #             "username",
        #             models.CharField(
        #                 },
        #                 ],
        #             ),
        #         ),
        #             "first_name",
        #             models.CharField(
        #             ),
        #         ),
        #             "last_name",
        #             models.CharField(
        #             ),
        #         ),
        #             "email",
        #             models.EmailField(
        #             ),
        #         ),
        #             "is_staff",
        #             models.BooleanField(
        #             ),
        #         ),
        #             "is_active",
        #             models.BooleanField(
        #             ),
        #         ),
        #             "date_joined",
        #             models.DateTimeField(
        #             ),
        #         ),
        #             "premium_active_from",
        #         ),
        #             "premium_cancelled_on",
        #         ),
        #             "groups",
        #             models.ManyToManyField(
        #             ),
        #         ),
        #             "user_permissions",
        #             models.ManyToManyField(
        #             ),
        #         ),
        #     ],
        #     },
        #     ],
        # ),
    ]
