# Generated by Django 4.0a1 on 2022-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
