# Generated by Django 4.0a1 on 2022-10-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_customuser_complete_name_customuser_generic_ads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='api_limited',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='api_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='api',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.apiclient'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='complete_name',
            field=models.TextField(blank=True, help_text='How would you like to be called?', verbose_name='Preferred name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='generic_ads',
            field=models.BooleanField(default=False, help_text='Show generic ads even if subscribed to premium'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_ads',
            field=models.BooleanField(default=False, help_text='Show job ads even if subscribed to premium'),
        ),
    ]
