# Generated by Django 4.0a1 on 2022-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0057_ad_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="consecutive_weeks",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
