# Generated by Django 4.0a1 on 2022-10-04 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_alter_ad_body_alter_ad_floss_repository_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="entry_created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ad",
            name="entry_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="body",
            field=models.TextField(help_text="Only <strong>plain text</strong> is accepted for now.\n        If you selected Twitter above please take in consideration character limits.", verbose_name="Ad message"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.customuser"),
        ),
    ]
