# Generated by Django 4.0a1 on 2022-10-04 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_alter_ad_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ad",
            name="floss_project",
            field=models.BooleanField(default=False, help_text="FLOSS projects get a 20% discount", verbose_name="FLOSS project"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="mastodon",
            field=models.BooleanField(default=False, help_text='Would you like to advertise on <a href="/social#mastodon" title="Mastodon bots">Mastodon</a>?'),
        ),
        migrations.AlterField(
            model_name="ad",
            name="newsletter",
            field=models.BooleanField(default=True, help_text='Would you like to advertise in the <a href="/weekly/" title="Weekly newsletters">newsletters</a>?<br/>\nIf you select multiple topics, duplicate emails are counted only once.\n        '),
        ),
        migrations.AlterField(
            model_name="ad",
            name="topics",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[("apl", "APL"), ("candcpp", "C & C++"), ("compsci", "Computer science"), ("devops", "DevOps"), ("erlang", "Erlang & Elixir"), ("golang", "Golang"), ("hackernews", "Hacker News"), ("haskell", "Haskell"), ("java", "Java"), ("laarc", "Laarc"), ("lisp", "Lisp & Scheme"), ("nim", "Nim"), ("php", "PHP"), ("programming", "Software Development"), ("python", "Python"), ("ruby", "Ruby"), ("rust", "Rust"), ("unix", "Unix"), ("webdev", "Web Development"), ("zig", "Zig")], max_length=255), blank=True, help_text="Ads are always reviewed manually and only ads relevant to the selected topics are approved", null=True, size=None),
        ),
        migrations.AlterField(
            model_name="ad",
            name="twitter",
            field=models.BooleanField(default=False, help_text='Would you like to advertise on <a href="/social#twitter" title="Twitter bots">Twitter</a>?'),
        ),
    ]
