# Generated by Django 4.0a1 on 2022-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_subscriber_subscribed_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
