# Generated by Django 4.0.8 on 2022-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_mention_mentionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentionnotification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
