# Generated by Django 4.0.8 on 2022-10-09 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0072_alter_mentionnotification_discussion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mention",
            name="platforms",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), blank=True, size=None),
        ),
    ]
