# Generated by Django 4.0.8 on 2022-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_alter_mention_base_url_alter_mention_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='pagerank',
            field=models.FloatField(null=True),
        ),
    ]
