# Generated by Django 4.0.8 on 2022-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0075_resource_pagerank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="pagerank",
            field=models.FloatField(default=0),
        ),
    ]
