# Generated by Django 4.1.7 on 2023-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0077_subscriber_suspected_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="http_headers",
            field=models.JSONField(null=True),
        ),
    ]
