# Generated by Django 4.1.7 on 2023-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0078_subscriber_http_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="aws_notification",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed_from",
            field=models.CharField(
                blank=True,
                choices=[("wf", "Web Form"), ("em", "Email Comand"), ("aws", "AWS")],
                max_length=3,
                null=True,
            ),
        ),
    ]
