# Generated by Django 4.1.7 on 2023-03-22 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0079_subscriber_aws_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="exclude_platforms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1),
                blank=True,
                help_text="\nPlatforms you are NOT interested in.\n        ",
                null=True,
                size=None,
            ),
        ),
    ]
