# Generated by Django 4.1.7 on 2023-03-27 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0081_apiclient_created_at_apiclient_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mention",
            name="subreddits_only",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="title_pattern",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="url_pattern",
        ),
        migrations.AddField(
            model_name="mention",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                help_text="\nComa separated list of keywords. The title of the <i>posted</i> story must contain <i>one</i> of these keywords. It could be your brand, name or a product you are interested in.\n        ",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="base_url",
            field=models.TextField(
                blank=True,
                help_text="\nThe discussed URL must have this prefix.</br>\nIt could be your website, your twitter profile, github profile, etc.<br/>\nFor example: xojoc.pw, twitter.com/XojocXojoc, github.com/xojoc<br/>\n\nCommon subdomains are ignored. So <i>example.com</i> matches <i>www.example.com</i>, <i>m.example.com</i>, <i>example.com</i>, etc.<br/>\nIf you have different subdomains (like blog. forum. docs. etc.) you have to create a separate rule for them.\n    ",
                verbose_name="URL prefix",
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="keyword",
            field=models.TextField(
                blank=True,
                help_text="\nThe title of the <i>posted</i> story must have this keyword. It could be your brand, name or a product you are interested in.\n    ",
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="subreddits_exclude",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="\nComa separated list of subreddits to ignore.\n        ",
                null=True,
                size=None,
                verbose_name="Subreddits blacklist",
            ),
        ),
    ]
