# Generated by Django 4.1.7 on 2023-03-28 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0082_remove_mention_subreddits_only_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mention",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disable"),
        ),
        migrations.AlterField(
            model_name="mention",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                help_text="\nComa separated list of keywords. The title of the <i>posted</i> story must contain <i>one</i> of these keywords. It could be your brand, your name or a product you are interested in.<br/>\nBoth the keyword and title of the thread are normalized. So the keywords <i>XOJOC,anotherkeyword</i> will match for example <i>Xojoc's new project</i>, etc.\n<br/>\nNo more than 3 keywords are allowed.\n        ",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="subreddits_exclude",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="\nComa separated list of subreddits to ignore.\n        ",
                null=True,
                size=None,
                verbose_name="Exclude subreddits",
            ),
        ),
    ]
