# Generated by Django 4.1.7 on 2023-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0084_subscriber_weeks_clicked"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed_feedback",
            field=models.TextField(null=True),
        ),
    ]
