# Generated by Django 4.1.7 on 2023-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0085_subscriber_unsubscribed_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="unsubscribed_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
