# Generated by Django 4.1.7 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0086_alter_subscriber_unsubscribed_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="unsubscribed_feedback",
            field=models.TextField(
                blank=True,
                help_text="Let us know how to improve.",
                null=True,
                verbose_name="Unsubscription reason",
            ),
        ),
    ]
