# Generated by Django 4.2.6 on 2023-10-14 15:06

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_alter_subscriber_unsubscribed_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='topics',
            field=web.models._CustomArrayField(base_field=models.CharField(choices=[('apl', 'APL'), ('candcpp', 'C & C++'), ('compsci', 'Computer science'), ('devops', 'DevOps'), ('erlang', 'Erlang & Elixir'), ('golang', 'Golang'), ('hackernews', 'Hacker News'), ('haskell', 'Haskell'), ('java', 'Java'), ('lisp', 'Lisp & Scheme'), ('nim', 'Nim'), ('php', 'PHP'), ('programming', 'Software Development'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('unix', 'Unix'), ('webdev', 'Web Development'), ('zig', 'Zig')], max_length=255), choices=[('apl', 'APL'), ('candcpp', 'C & C++'), ('compsci', 'Computer science'), ('devops', 'DevOps'), ('erlang', 'Erlang & Elixir'), ('golang', 'Golang'), ('hackernews', 'Hacker News'), ('haskell', 'Haskell'), ('java', 'Java'), ('lisp', 'Lisp & Scheme'), ('nim', 'Nim'), ('php', 'PHP'), ('programming', 'Software Development'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('unix', 'Unix'), ('webdev', 'Web Development'), ('zig', 'Zig')], default=['apl'], help_text='Ads are always reviewed manually and only ads relevant to the selected topics are approved', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='topic',
            field=models.CharField(choices=[('apl', 'APL'), ('candcpp', 'C & C++'), ('compsci', 'Computer science'), ('devops', 'DevOps'), ('erlang', 'Erlang & Elixir'), ('golang', 'Golang'), ('hackernews', 'Hacker News'), ('haskell', 'Haskell'), ('java', 'Java'), ('lisp', 'Lisp & Scheme'), ('nim', 'Nim'), ('php', 'PHP'), ('programming', 'Software Development'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('unix', 'Unix'), ('webdev', 'Web Development'), ('zig', 'Zig')], max_length=255),
        ),
    ]
