# Generated by Django 4.2.6 on 2023-10-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_alter_ad_topics_alter_subscriber_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='email',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='token',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='url',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rss_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='anchor_rel',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='anchor_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='anchor_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='canonical_url',
            field=models.CharField(blank=True, default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='clean_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='excerpt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='normalized_title',
            field=models.CharField(blank=True, default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_from',
            field=models.CharField(blank=True, choices=[('wf', 'Web Form'), ('em', 'Email Comand')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_feedback',
            field=models.TextField(blank=True, default='', help_text='Let us know how to improve.', verbose_name='Unsubscription reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_from',
            field=models.CharField(blank=True, choices=[('wf', 'Web Form'), ('em', 'Email Comand'), ('aws', 'AWS')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
