# Generated by Django 4.2.6 on 2023-10-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0089_alter_apiclient_email_alter_apiclient_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='platform',
            new_name='_platform',
        ),
    ]
