# Generated by Django 4.2.6 on 2023-10-15 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0090_rename_platform_discussion__platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="category",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discussion",
            name="normalized_title",
            field=models.CharField(blank=True, default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discussion",
            name="title",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mention",
            name="exclude_platforms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("h", "Hacker News"),
                        ("u", "Lambda the Ultimate"),
                        ("r", "Reddit"),
                        ("l", "Lobsters"),
                        ("b", "Barnacles"),
                        ("g", "Gambero"),
                        ("t", "Tilde news"),
                        ("s", "Standard"),
                        ("e", "Echo JS"),
                        ("a", "Laarc"),
                    ],
                    max_length=1,
                ),
                blank=True,
                help_text="\nPlatforms you are NOT interested in.\n        ",
                null=True,
                size=None,
            ),
        ),
    ]
