# Generated by Django 4.2.6 on 2023-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0091_alter_discussion_canonical_redirect_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comments for the ad approver.<br/>\nIf you have preferences for when to tweet or toot or anything else let us know here.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="floss_repository",
            field=models.TextField(
                blank=True,
                default="",
                help_text="FLOSS projects get a 20% discount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="url",
            field=models.TextField(
                blank=True, default="", verbose_name="Ad URL"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discussion",
            name="canonical_redirect_url",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
