# Generated by Django 4.2.6 on 2023-10-15 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0092_alter_ad_comments_alter_ad_floss_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='normalized_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
            preserve_default=False,
        ),
    ]
