# Generated by Django 4.2.6 on 2023-10-15 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0093_alter_discussion_normalized_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='normalized_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
            preserve_default=False,
        ),
    ]
