# Generated by Django 4.2.6 on 2023-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0094_alter_resource_normalized_tags_alter_resource_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField()),
                ('value_json', models.JSONField()),
                ('entry_created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
