# Generated by Django 4.2.6 on 2023-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0097_alter_mastodonpost_bot_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='category',
        ),
        migrations.AddField(
            model_name='discussion',
            name='_category',
            field=models.IntegerField(default=0),
        ),
    ]
